// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJcQp-YuL8g8gubHUpJvXvPUypXDs7ts',
    appId: '1:857270039324:web:69e4b9fa4f7e56a1ff80d9',
    messagingSenderId: '857270039324',
    projectId: 'my-online-app-1',
    authDomain: 'my-online-app-1.firebaseapp.com',
    storageBucket: 'my-online-app-1.firebasestorage.app',
    measurementId: 'G-NNSCHKK1DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhU6q0iksosIVb5fEg2cObmhmY3sC-so',
    appId: '1:857270039324:android:2eaa5a3f65f7fd30ff80d9',
    messagingSenderId: '857270039324',
    projectId: 'my-online-app-1',
    storageBucket: 'my-online-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3s8yHspHReptCy-wMyZ-R4wsP4dy5oaM',
    appId: '1:857270039324:ios:36687976a7ac6ab8ff80d9',
    messagingSenderId: '857270039324',
    projectId: 'my-online-app-1',
    storageBucket: 'my-online-app-1.firebasestorage.app',
    iosBundleId: 'com.example.tgBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3s8yHspHReptCy-wMyZ-R4wsP4dy5oaM',
    appId: '1:857270039324:ios:36687976a7ac6ab8ff80d9',
    messagingSenderId: '857270039324',
    projectId: 'my-online-app-1',
    storageBucket: 'my-online-app-1.firebasestorage.app',
    iosBundleId: 'com.example.tgBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQrLBsxMI511LvlKQFrxl_00mD0jTFLwI',
    appId: '1:857270039324:web:023e44a17c791946ff80d9',
    messagingSenderId: '857270039324',
    projectId: 'my-online-app-1',
    authDomain: 'my-online-app-1.firebaseapp.com',
    storageBucket: 'my-online-app-1.firebasestorage.app',
    measurementId: 'G-4NE5ZXR8LZ',
  );
}
